name: cicly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^9.0.5
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  material_symbols_icons: ^4.2874.0
  sqflite: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true